### ISSUE TITLE
Emscripten version 3.1.42 and up cause errors in the js output

### ISSUE THREAD

**Issue by NTM-Adam** [Wasted-Audio/hvcc#111]
When compiling patches with emscripten versions > 3.1.41, the outputted js wrapper throws errors such as the following:

Converting base64 string to bytes failed

Upon debugging, it appears there was a reference error around the atob() function, previous versions included a fallback for this function in the compiled output.

**Comment by dromer** [comment]
Hmm, possibly we just need to add it to `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` section?

**Comment by dromer** [comment]
This possibly got fixed here: https://github.com/emscripten-core/emscripten/pull/20587

**Comment by dromer** [comment]
@NTM-Adam did you get a chance to try latest emscripten yet?

**Comment by dromer** [comment]
Hmm, I just tested with `3.1.50` and I still see `ReferenceError: atob is not defined` in the console.
