### ISSUE TITLE
Supporting some of the yet unsupported vanilla objects

### ISSUE THREAD

**Issue by sonicdebris** [Wasted-Audio/hvcc#116]
Is the support for the yet unsupported vanilla objects possible in theory, or is there some major road-blocker? It would be nice to have support for expr~, fexpr~, fft~ and ifft~, these object alone might open up a lot of possibilities with patching.

If I understand correctly, hvcc is just reading the pure data patches and providing completely custom implementations for the various objects, but would it be possible to at least partially "copy" and reuse the original code for some of those more advanced objects? Would there be licensing issues, or technical issues that have already been evaluated and deemed too complex to overcome?

I am poking the code base to try and understand how one would introduce support for a new object, if anyone has any tips to get started with the architecture and on development and testing practices within the project, it would be much appreciated!

**Comment by dromer** [comment]
Please have a look at the discussion section for topics related to this: https://github.com/Wasted-Audio/hvcc/discussions
Or start a new discussion about a specific topic there.

(so we can have the Issue tracker for bugs/issues)
