### ISSUE TITLE
Feature request: ability to change samplerate and blocksize for Daisy

### ISSUE THREAD

**Issue by crewdson86** [Wasted-Audio/hvcc#121]
my reason being that i'm tackling the well documented digital noise (https://forum.electro-smith.com/t/questions-about-digital-noise-and-grounding/432/83) that the Daisy Seed can produce when used in a purpose built circuit. On the forum thread linked above there are lots of suggestions for hardware/circuit based solutions to try and reduce the noise but some people have also had success with changing the blocksize and/or moving specific things around in the code such as moving LED function from the main loop to the AudioCallback. 

I wondered if there was a way for me to try these solutions given the fact that I'm using pd2dsy.

**Comment by dromer** [comment]
Do note that pd2dsy is not actively being worked on, this will soon be superseded by plugdata as the preferred method for building/flashing to Daisy for novices.

json2daisy exposes 2 functions for setting the samplerate and blocksize:
https://github.com/electro-smith/json2daisy/blob/main/src/json2daisy/templates/daisy.h#L292
https://github.com/electro-smith/json2daisy/blob/main/src/json2daisy/templates/daisy.h#L316

We need to come up with a clean method to use these functions when requested. I think we should probably just add 2 new fields to the metadata.json to "activate" these. Of course it will also require some testing to make sure these work correctly.
