### ISSUE TITLE
91mError: Connection graph connects to out-of-range let

### ISSUE THREAD

**Issue by TricksterSam** [Wasted-Audio/hvcc#157]
I'm running plugdata 0.8.0 in PopOS. I'm compiling Electro-Smith Daisy code with the versio.json. Compilation failed with this error:

`--> Generating C
  1) [91mError[0m hv2ir: Connection [__graph.9fd2qQ6k(temp_cc6ab1b0.hv.json/palme_diffuseur):1] --> [__graph.6pbV7FFC(temp_cc6ab1b0.hv.json/palme_diffuseur):1] connects to out-of-range let.
Total compile time: 8710.50ms
Compiling...make: /tmp/Heavy-ad409ca0329a7eaa8f15ac/daisy/source/Makefile: No such file or directory
make: *** No rule to make target '/tmp/Heavy-ad409ca0329a7eaa8f15ac/daisy/source/Makefile'.  Stop.`

Once, I went through and deleted a bunch of objects that weren't relevant--I was adapting my patch to Daisy and had a lot of other code related to MIDI inputs--this error went away.

Not sure what caused it, but the folks at PlugData Discord suggested that I report it.

**Comment by dromer** [comment]
`0.8.0` is very old, you should at least update to `0.8.2`

**Comment by dromer** [comment]
We're you perhaps using `[stripnote]`?
In an upcoming release we'll have fixed the usage of the right inlet.

Until then you'll have to use a `[pack f f]` to direct both note and velocity values to the left inlet.

**Comment by dromer** [comment]
Not enough info given.
