### ISSUE TITLE
How to implement DPF output parameters on PD patches?

### ISSUE THREAD

**Issue by AnClark** [Wasted-Audio/hvcc#164]
Hi Dreamer,

DPF supports `kParameterIsOutput`. If PD patches has output parameters (e.g. output level), this would be useful.

I've found that in `hvcc/generators/c2dpf/templates/initParameter.cpp`, there's already an implementation for it:

```c++
      {%- if v.type == "send" %}
        parameter.hints = kParameterIsOutput
      {%- else %}
        parameter.hints = kParameterIsAutomatable
      {%- endif %}
```

But I cannot find any documents, or object in HeavyLib to implement it in my patch.

Do you have any ideas?

**Comment by dromer** [comment]
Simply create a send object like `[s OutputLevel @hv_param]`.

You will need to take care that your receive and output parameters have unique names and do not clash.

Good luck.

**Comment by AnClark** [comment]
Thanks a lot!
