### ISSUE TITLE
snapshot~ has some delay when banged

### ISSUE THREAD

**Issue by Borey345** [Wasted-Audio/hvcc#172]
I cannot attach a patch, but it is quite simple.

![image](https://github.com/Wasted-Audio/hvcc/assets/6347716/ffb52185-f3c7-412c-90a0-0405c12ccbe1)

The first dac~ channel gives 5, as expected, but the second gives 2, which means, snapshot~ bang does not output a value prior to the right bang.

![image](https://github.com/Wasted-Audio/hvcc/assets/6347716/ce7cfec4-8951-4761-af30-45b27e7d15f5)

Would be nice, if you have some workaround suggestions.

**Comment by dromer** [comment]
How does this behave in Pd?

And just to understand the context: which generator are you using?

**Comment by dromer** [comment]
Btw considering how signal v control connections work I don't think one could expect any different behavior. Basically the control message coming out of `snapshot~` is scheduled for the next audio cycle, but the bang to `2` message is still scheduled for the current one. So these messages can never arrive in the order that you expect.

Probably the only way to correct this is to wire this differently. Perhaps like this:
https://i.imgur.com/8jeWgRB.png

You're still going to be one audio cycle "late", but at least your calculation will work correctly.

**Comment by Borey345** [comment]
> How does this behave in Pd?

In Pd the it works just like the left chain connected to the first dac~ inlet: first the right inlet of the [+~] is updated then, it is calculated to 5.

> And just to understand the context: which generator are you using?
I generate C++ code, then compile in VS2019.

**Comment by Borey345** [comment]
> Btw considering how signal v control connections work I don't think one could expect any different behavior. Basically the control message coming out of `snapshot~` is scheduled for the next audio cycle, but the bang to `2` message is still scheduled for the current one. So these messages can never arrive in the order that you expect.
> 
> Probably the only way to correct this is to wire this differently. Perhaps like this: ![](https://camo.githubusercontent.com/37fdd68453f935ae6e3eee2cdf5361494c21c66e908feef21f1b81bc9afc77e3/68747470733a2f2f692e696d6775722e636f6d2f386a65576752422e706e67)
> 
> Or a bit simpler: ![](https://camo.githubusercontent.com/a3dcbae159993330a287491dbd4066648bc6afa66ffa927450f6601a78882c2b/68747470733a2f2f692e696d6775722e636f6d2f476b656563674c2e706e67)
> 
> You're still going to be one audio cycle "late", but at least your calculation will work correctly.

Thanks, I will try this, but my patch is just a simple test patch, I came up to it from more serious one, where the issue occured. Anyways, I probably can try to apply this approach.

**Comment by Borey345** [comment]
> Btw considering how signal v control connections work I don't think one could expect any different behavior. Basically the control message coming out of `snapshot~` is scheduled for the next audio cycle, but the bang to `2` message is still scheduled for the current one. So these messages can never arrive in the order that you expect.

Just rechecked: it evaluates to 5 in Pd, which means snapshot result is propagated before the '2' message. In Heavy, it evaluates to 2.
![image](https://github.com/Wasted-Audio/hvcc/assets/6347716/99d926c1-9821-4099-bd60-6e0348ec2abd)

**Comment by dromer** [comment]
As said: due to how signal and control objects are evaluated the output message of this object is scheduled for the next audio cycle, which will be later than the 2 message:

https://github.com/Wasted-Audio/hvcc/blob/develop/hvcc/generators/ir2c/static/HvSignalSample.c#L46

It is not possible to change this behavior, but you can try the other patch suggestion to get the order of control messages aligned.

**Comment by dromer** [comment]
Hmmm, I'm now running a quick test and I'm not getting _any_ output from `snapshot~` which is strange :thinking: 

I'm sure that I've used it before, albeit not done any extensive testing.
This will need some closer investigation to understand why it is not outputting any values at all ..

**Comment by Borey345** [comment]
This is strange. I do have an output from `snapshot~`.

I managed to workaround the delay issue. But the workaround is kind of ugly. I had to even introduce a small signal delay line to make it work.

Anyways, left-to-right calculation with `trigger~` is a very basic Pd concept, so I guess this issue needs to be addressed somehow.

BTW, I just found out that `log 10` gives natural logarithm in Heavy. In Pd it is logarithm of base 10. It can be easily worked around, but still I suggest to create an issue about it later..

**Comment by dromer** [comment]
`trigger~` does not exist :)

The control-flow execution is correct, but as I said `snapshot~` output happens on the next block. This cannot be changed.

**Comment by Borey345** [comment]
> `trigger~` does not exist :)

Sorry, I mean `t b b` thing, without ~.

> The control-flow execution is correct

I would agree with you, if it worked the same as in Pd. But it is not.

**Comment by dromer** [comment]
> I would agree with you, if it worked the same as in Pd. But it is not.

This depends on your definition of "it". `snapshot~` is not a control object, so it doesn't behave like one.
