### ISSUE TITLE
[wasm] - [noise~] becomes high pitch at higher amplitudes in Microsoft Edge (Windows 11)

### ISSUE THREAD

**Issue by diemildefreude** [Wasted-Audio/hvcc#181]
With a simple patch of just `[noise~]->[*~]->[dac~]`, with `[*~]` taking a volume value, if the volume is set to 1.0, the noise immediately changes into something like a sustained, very high-pitched sine wave. If the volume is set to 0.9, the same thing happens, but it takes around 10 seconds of noise before the change occurs. 0.5 is stable and doesn't produce this bug.

Firefox does not have this problem.

**Comment by dromer** [comment]
I assume that this is with AudioWorklet. What if you force using AudioLib, does it give the same result?

You can do this by setting this variable to `false`: https://github.com/Wasted-Audio/hvcc/blob/develop/hvcc/generators/c2js/template/hv_wrapper.js#L3

**Comment by diemildefreude** [comment]
Yeah, I'm getting the same bug with ScriptProcessorNode/audiolib too.

Also, once it happens, I can't turn off the audio with the generated index.html's start/stop transport (loader.stop() call). The high pitch remains.

**Comment by dromer** [comment]
Hmm, that's one very strange bug and not sure if it's something that we can really do anything about.
