### ISSUE TITLE
[wwise] - Event is not sent with a bang

### ISSUE THREAD

**Issue by gfazzito** [Wasted-Audio/hvcc#190]
In the Wwise integrations, if the [s @hv_event] receives a bang , it doesn't activate the event

![image](https://github.com/user-attachments/assets/3dd7225c-f28b-44df-b11f-236e5d423559)

From [this discussion](https://discord.com/channels/705820271910715474/939227639057641542/1187370193350045696), the problem is in HvccTestEventSource.cpp. Changing the conditional to "if (pPlugin != nullptr)" should solve it, as the event is being triggered from any input.

![image](https://github.com/user-attachments/assets/c86b470f-166f-4701-9e2b-73c361f7858a)

**Comment by dromer** [comment]
So that would be this code in the template: https://github.com/Wasted-Audio/hvcc/blob/develop/hvcc/generators/c2wwise/templates/SoundEnginePlugin/%7B%7Bname%7D%7D%7B%7Bplugin_type%7D%7D.cpp#L97-L115

**Comment by dromer** [comment]
@gfazzito are you able to test a custom branch? I hope that this PR will fix it: https://github.com/Wasted-Audio/hvcc/pull/193

**Comment by gfazzito** [comment]
will pull and I'll tell you

**Comment by dromer** [comment]
@gfazzito latest develop branch then. This is now merged :)
