### ISSUE TITLE
add midirealtimein

### ISSUE THREAD

**Issue by dromer** [Wasted-Audio/hvcc#27]
I find that I'd really like to work with real-time midi messages, like clock signals

Any ideas how to add this?

**Comment by CarloCattano** [comment]
In theory is not super difficult if you just need the 3 main messages , stop play clock-pulse. 
Sometimes it can be done with the sendCC function just by replacing the bytes , so this usually work :
 ```  
void sendCC(uint8_t channel, uint8_t control, uint8_t value)
//Duplicate to 
void sendClockPulse(248, 0 , 0)
void sendStart(250, 0, 0)
void sendStop(252, 0, 0)
``` 
    ---[detailed specs here](https://en.wikipedia.org/wiki/MIDI_beat_clock) 
This effectively sends a single clock pulse that is easily synced in the patch to send at the right intervals for the desired midi output.

Im talking in general here did not looked into hvcc code itself, and this solution does not provide timecode etc

**Comment by CarloCattano** [comment]
Leving this test patch here for the future in case we get some time to try and get this goin
[clock_out_test.zip](https://github.com/Wasted-Audio/hvcc/files/7359000/clock_out_test.zip)
g

**Comment by CarloCattano** [comment]
Hope to see this project going , thanks for bringing it back to live and python3  ! 

>  Your example of course does require us to get [expr]

Not really , ignore that example , that expr its just there to calculate bpm . If you have pd as a midi *master* or *main* you dont need it , can be done diferently

**Comment by CarloCattano** [comment]
What about this example Using an audio signal as a clock source @dromer  ?

[audio_to_midi_ClockOut.zip](https://github.com/Wasted-Audio/hvcc/files/7359651/audio_to_midi_ClockOut.zip)

**Comment by dromer** [comment]
This is now fixed in develop. With DPF we even get transport signals (not all of them yet, but start/stop + "sample accurate" clock).

Closing issue.
