### ISSUE TITLE
Strings must be encoded before hashing

### ISSUE THREAD

**Issue by DaniKog** [Wasted-Audio/hvcc#67]
**Error 1** 
When running _c2Wwise.py_ getting the first error I am getting is 

> plugin_id = int(hashlib.md5(patch_name).hexdigest()[:4], 16) & 0x7FFF  # unique id from patch name [0...32767]
> TypeError: Strings must be encoded before hashing

 
 This can be easily fixed by adding `.encode('utf-8-sig')` to line 66 in _c2Wwise.py_ 
`plugin_id = int(hashlib.md5(patch_name.encode('utf-8-sig')).hexdigest()[:4], 16) & 0x7FFF  # unique id from patch name [0...32767]`

**Error 2** 
After this getting a similar error
> 1) ←[91mError←[0m c2wwise: Strings must be encoded before hashing

Isolated this to be coming from line 166 c2Wwise.py_ when passing the files to the writer
```
                with open(file_path, "w") as g:
                  g.write(env.get_template(f).render(
                      name=patch_name,
                      parameters=in_parameter_list,
                      sends=out_parameter_list,
                      events=event_list,
                      tables=table_list,
                      plugin_type=plugin_type,
                      plugin_id=plugin_id,
                      wwise_version=wwise_sdk_version,
                      msbuild_version="140",
                      files=files)) <--------------      line 166
```                 
                      
The issue is only present when writing a _.pbxproj_ file for the xcode project. I managed to bypass it by just removing the creation of this file as I develop on Visual Studio.

I an not sure how to fix this one
Was thinking they should probably be fixed in the same commit as they seems related

Thank you

**Comment by dromer** [comment]
I've been thinking to deprecate all `.pbxproj` usage as there is nobody to support it.
(I mostly use vim and vscode)

**Comment by DaniKog** [comment]
Is it causing other issues? 
With other generators?

**Comment by dromer** [comment]
No, it's more that nobody can confirm if it even works and I don't want to support it :)
Just general cleanup to remove those files.

**Comment by DaniKog** [comment]
Seems sad to remove a platform if it is just the string hashing
I will try to see if someone on Mac can verify it works

Or maybe instead of removing making it an argument so it is disabled by default until it can be supported

**Comment by dromer** [comment]
No I will fix the string hash, have a typing branch where it's already resolved.

I was talking about the `.pbxproj` files which are for Xcode projects and I have no way to support this.

**Comment by DaniKog** [comment]
I see maybe comment it out then until can be supported 
it is up to you just think it is unfortunate to remove a platform because no one on the repo is using it

**Comment by dromer** [comment]
I'm not removing a platform, just highly specific Xcode IDE "support" which literally is unsupported and gives problems :)

**Comment by DaniKog** [comment]
Ah right can still use Visual Studio on Mac 😇

**Comment by dromer** [comment]
fixed in https://github.com/Wasted-Audio/hvcc/commit/51de4ff7170ac2522bfd4262709b4c2be1ef18b1
