### ISSUE TITLE
Issues with [pow~]

### ISSUE THREAD

**Issue by GModal** [Wasted-Audio/hvcc#92]
Possibly a bug with the [pow~] object?

When used to create a exponential-type of envelope, i.e., feed output of [line~] into [pow~] and have it drive a level `[*~]`, a LOT of clicks and xruns are generated. No issues with the patch in PureData. Don't see any weird values sent to line~ (nothing large or neg).

But inserting a [max~] object between [pow~] and `[*~]` fixes it; the [max~] levels are kept a fraction above zero (like 1e-07).

Actually, a test with just [max~ 0] in between seems OK, too.

**Comment by dromer** [comment]
[pow~] implementation depends on the architecture: https://github.com/Wasted-Audio/hvcc/blob/develop/hvcc/generators/ir2c/static/HvMath.h#L536
So I wonder if this is the case for all

Can you give an example patch that clearly shows this behavior?
Unfortunately we still don't have proper tests for signal objects yet, but would be good as reference.

**Comment by GModal** [comment]
Should have mentioned it's Ubuntu 22.04.1 LTS. (Did I post this yesterday? If so, I forgot to send the comment...)

Try this patch. I'm not seeing the xruns now, but the click, yes.
[env.zip](https://github.com/Wasted-Audio/hvcc/files/10715068/env.zip)

**Comment by dromer** [comment]
Tried this with the DPF exporter on my machine and can definitely reproduce. No idea how/why yet though.

**Comment by dromer** [comment]
Hmm, interestingly, the [pow~] in heavy expects a control input on the right inlet. Even though in pd it's supposed to be a signal (according to the docs).

**Comment by dromer** [comment]
Did a little test and changing the implementation to
```c
#define hv_pow_f(a, b) fmaxf(powf(a, b), 0)
``` 

(basically forcing a `[max 0]`) makes the behavior go away.

Need to investigate if this really is the proper solution and doesn't cause any other issues along the way.

**Comment by GModal** [comment]
Ah, cool. Good catch, thank you.

I noticed a couple other wrinkles to this:
1) If `[adc~]` is replaced with `[osc~]` , the issue doesn't seem to manifest. Very limited testing on this.
2) The Heavy Lib `[hv.pow]` "replacement" object for `[pow~]` does show the same bug.

**Comment by dromer** [comment]
btw I noticed that `hv.pow~` does include a `[max 0]` on the input:

![](https://i.imgur.com/vnJwzZw.png)

**Comment by mhroth** [comment]
@GModal have you compiled for AVX in your build?

**Comment by dromer** [comment]
I am actually no longer able to reproduce the issue. Using the same test-patch and DPF exporter the output does not have any crackles.

**Comment by dromer** [comment]
@GModal I really can't reproduce this any more.

Please try again using latest tooling (ie. latest plugdata toolchain) and let us know.
Will reopen if you are still experiencing problems.
