### ISSUE TITLE
is this no longer a enzienaudio/hvcc fork?

### ISSUE THREAD

**Issue by giuliomoro** [Wasted-Audio/hvcc#95]
I used to be able to open PRs to this repo from my fork https://github.com/giuliomoro/hvcc/ of https://github.com/enzienaudio/hvcc/ , however this is no longer the case. 

What happened? I have a couple of useful commits https://github.com/giuliomoro/hvcc/tree/fix-X-f

**Comment by dromer** [comment]
I have decoupled from the other repo as they will never see activity or merge any PRs.
It makes this repo a lot cleaner and easier to manage without having dependencies on an upstream that doesn't actually exist.

**Comment by giuliomoro** [comment]
Guess I will need to make a fork of this one now
